# Generated by Django 6.0.2 on 2026-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='dodo_payment_id',
            field=models.CharField(blank=True, help_text='Dodo Payments Payment ID', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('dodo', 'Dodo Payments')], max_length=20),
        ),
    ]
