# Generated by Django 6.0.2 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_validstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=True, help_text='Receive offer notifications via WhatsApp'),
        ),
    ]
