# Generated by Django 4.2.27 on 2026-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_per_user',
            field=models.BooleanField(default=True, help_text='Each user can use this coupon only once'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='single_item_only',
            field=models.BooleanField(default=False, help_text='Discount applies to one item only (cheapest)'),
        ),
    ]
