# Generated by Django 6.0.2 on 2026-03-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Offer headline, e.g. '50% OFF on Breakfast!'", max_length=200)),
                ('description', models.TextField(help_text='Offer details shown in the message body')),
                ('discount_code', models.CharField(blank=True, help_text='Optional coupon code', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Optional offer banner image', null=True, upload_to='offers/')),
                ('valid_from', models.DateTimeField(help_text='When the offer starts')),
                ('valid_until', models.DateTimeField(help_text='When the offer expires')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('dry_run', 'Dry Run')], default='sent', max_length=10)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Message ID from WhatsApp API', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='notifications.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
